# Generated by Django 5.0.3 on 2024-03-16 17:20

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='profiles/brand_logos/')),
                ('headline', models.TextField(blank=True, max_length=200, null=True)),
                ('tagline', models.TextField(blank=True, max_length=200, null=True)),
                ('website', models.URLField(blank=True, max_length=100, null=True)),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('about_brand', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand_Shop_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=150)),
                ('register_type', models.CharField(choices=[('select', 'select'), ('plc', 'Public Limited Company'), ('pvt', 'Private Limited Company'), ('opc', 'One-person Company'), ('llp', 'Limited Liability Partnership'), ('pf', 'Partnership Firm'), ('sp', 'Sole Proprietorship')], default='select', max_length=50)),
                ('gst_no', models.CharField(max_length=100)),
                ('company_pan_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('user_type', models.CharField(choices=[('private', 'Private Account'), ('creator', 'Creator Account'), ('brand', 'Brand Account')], default='private', max_length=20)),
                ('profile_image', models.ImageField(blank=True, default='', null=True, upload_to='profiles/profile_images/')),
                ('cover', models.ImageField(blank=True, default='', null=True, upload_to='profiles/profile_cover/')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Select')], default='N', max_length=1, null=True)),
                ('headline', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('about', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('about_image', models.ImageField(blank=True, default='', null=True, upload_to='profiles/about_profile_images/')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
